add gitignore explicitly
plone/create-volto-app pull request #8
Opened 2019-02-20 12:04 UTC by nileshgulia1

2019-02-20 12:30 UTC, sneridagh requested changes
See comments

2019-02-20 12:30 UTC, sneridagh commented on lib/utils/copy-dir.js
> +          path.resolve(projectPath, "./.gitignore"),
Moving the same file into the same file?

2019-02-20 12:30 UTC, sneridagh commented on lib/utils/copy-dir.js
> +          path.resolve(projectPath, "./.gitignore"),
When it's packaged, the .gitignore will be gone, so you have to have it (in volto-starter-kit) as gitignore (as the CRA guys does), then move it once the folder is copied over

2019-02-21 06:33 UTC, nileshgulia1 commented
@sneridagh It works now.

2019-02-21 09:24 UTC, merged

2019-02-21 09:24 UTC, sneridagh commented
This fixed #5